# RPM spec for search-tool-ec2logshipper.
# _version is passed in from the Makefile via rpmbuild --define.
%global debug_package %{nil}

Name:           search-tool-ec2logshipper
Version:        %{_version}
Release:        1%{?dist}
Summary:        EC2 log shipper to AWS CloudWatch Logs
License:        MIT
Source0:        %{name}-%{version}.tar.gz

# Build/runtime dependencies.
BuildRequires:  golang >= 1.26
BuildRequires:  systemd
Requires:       systemd

%description
search-tool-ec2logshipper tails a log file on EC2 and forwards each line to
AWS CloudWatch Logs using the EC2 instance metadata service v2.

# Unpack the source tarball generated by the Makefile.
%prep
%setup -q

# Compile the Go binary inside the RPM build root.
%build
go build -o ec2logshipper .

# Install the binary, systemd unit, and an example config file.
%install
install -D -m 0755 ec2logshipper %{buildroot}%{_bindir}/ec2logshipper
install -D -m 0644 packaging/systemd/search-tool-ec2logshipper.service %{buildroot}/usr/lib/systemd/system/search-tool-ec2logshipper.service
install -D -m 0644 config.json.example %{buildroot}%{_sysconfdir}/%{name}/config.json

# Files owned by the resulting RPM package.
%files
%{_bindir}/ec2logshipper
/usr/lib/systemd/system/search-tool-ec2logshipper.service
%config(noreplace) %{_sysconfdir}/%{name}/config.json
